// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdV4CVmSCOeB6Ex_xJ0J8tq2crTtFuPMM',
    appId: '1:845989743979:web:08f039635d725ce322902e',
    messagingSenderId: '845989743979',
    projectId: 'fir-tutorial-7c0cb',
    authDomain: 'fir-tutorial-7c0cb.firebaseapp.com',
    storageBucket: 'fir-tutorial-7c0cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfr0cypatn6EqC8Zg9Ebx6JGes1IMWRLY',
    appId: '1:845989743979:android:5aa9bc95082a577722902e',
    messagingSenderId: '845989743979',
    projectId: 'fir-tutorial-7c0cb',
    storageBucket: 'fir-tutorial-7c0cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxDmHrtyEJShOL331gFFNdbzol8bD2jH8',
    appId: '1:845989743979:ios:181ed772bc5a976222902e',
    messagingSenderId: '845989743979',
    projectId: 'fir-tutorial-7c0cb',
    storageBucket: 'fir-tutorial-7c0cb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxDmHrtyEJShOL331gFFNdbzol8bD2jH8',
    appId: '1:845989743979:ios:181ed772bc5a976222902e',
    messagingSenderId: '845989743979',
    projectId: 'fir-tutorial-7c0cb',
    storageBucket: 'fir-tutorial-7c0cb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdV4CVmSCOeB6Ex_xJ0J8tq2crTtFuPMM',
    appId: '1:845989743979:web:7ffdecd3f0cc3ddf22902e',
    messagingSenderId: '845989743979',
    projectId: 'fir-tutorial-7c0cb',
    authDomain: 'fir-tutorial-7c0cb.firebaseapp.com',
    storageBucket: 'fir-tutorial-7c0cb.firebasestorage.app',
  );

}